<?php

namespace Webacademie\IntranetBundle\Repository;

/**
 * WebacademieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebacademieRepository extends \Doctrine\ORM\EntityRepository
{
}
