<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxiurdi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxiurdi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRxiurdi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRxiurdi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRxiurdi\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rxiurdi',
    'container.build_id' => 'c62bec87',
    'container.build_time' => 1539906238,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxiurdi');
